// <auto-generated />
namespace BikeFit2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Addaerobardetailstocontext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addaerobardetailstocontext));
        
        string IMigrationMetadata.Id
        {
            get { return "201410101245328_Add aerobar details to context"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
