// <auto-generated />
namespace BikeFit2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addstemheight : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstemheight));
        
        string IMigrationMetadata.Id
        {
            get { return "201410131348488_add stem height"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
